backend:
  name: git-gateway

media_folder: "site/static/img"
public_folder: "img"

collections:
  - name: "mattress"
    label: "Mattress"
    folder: "site/content/mattress"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Size", name: "size", widget: "select", options: ["Double", "King", "Super King"]}
      - {label: "Body", name: "body", widget: "markdown"}